"""Initial migration - create pastes table with token as PK

Revision ID: 67860367e893
Revises:
Create Date: 2025-11-29 15:56:45.469925

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '67860367e893'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pastes',
        sa.Column('token', sa.String(length=11), nullable=False),
        sa.Column('snowflake_id', sa.BigInteger(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('content_type', sa.String(length=255), nullable=False),
        sa.Column('size_bytes', sa.Integer(), nullable=False),
        sa.Column('sha256', sa.String(length=64), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('token'),
    )
    op.create_index(op.f('ix_pastes_expires_at'), 'pastes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_pastes_snowflake_id'), 'pastes', ['snowflake_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pastes_snowflake_id'), table_name='pastes')
    op.drop_index(op.f('ix_pastes_expires_at'), table_name='pastes')
    op.drop_table('pastes')
    # ### end Alembic commands ###
